# Generated by Django 4.0.3 on 2022-06-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(auto_created=True, blank=True, default=48658624640054, max_length=100),
        ),
    ]
