# Generated by Django 4.0.3 on 2022-06-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('case_discription', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('policy_code', models.IntegerField(auto_created=True, blank=True, default=48658624640054)),
                ('policy_type_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('type_name', models.CharField(choices=[('1', 'MotoInsurance'), ('2', 'LifeInsurance'), ('3', 'HomeInsurance'), ('3', 'HealthInsurance')], max_length=60)),
                ('description', models.TextField(max_length=100)),
                ('has_expired', models.BooleanField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quarterly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('yearly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('terms', models.TextField(max_length=400)),
                ('details', models.TextField(max_length=400)),
                ('is_available', models.CharField(default='Available', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_code', models.IntegerField(auto_created=True, blank=True, default=138734817278213229)),
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('date_signed', models.DateField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium', models.PositiveIntegerField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.case')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('policy_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policytype')),
            ],
        ),
    ]
