# Generated by Django 4.0.3 on 2022-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_code',
            field=models.CharField(auto_created=True, blank=True, default=138734400319100836, max_length=100),
        ),
    ]
