# Generated by Django 3.0.3 on 2022-04-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='d_o_b',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='f_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='l_name',
            new_name='other_name',
        ),
    ]
