# Generated by Django 3.0.3 on 2022-04-05 21:19

from email.policy import default
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
