# Generated by Django 3.0.3 on 2022-04-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220405_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
    ]
