# Generated by Django 4.0.3 on 2022-04-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_client_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
