# Generated by Django 4.0.3 on 2022-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivers_license', models.FileField(upload_to='doc/')),
                ('passport', models.FileField(upload_to='doc/')),
                ('adhaar', models.FileField(upload_to='doc/')),
                ('pan_card', models.FileField(upload_to='doc/')),
                ('salary_slip', models.FileField(upload_to='doc/')),
                ('bank_statement', models.FileField(upload_to='doc/')),
                ('itr', models.FileField(upload_to='doc/')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
