# Generated by Django 4.0.3 on 2022-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeInsurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdoc',
            old_name='adhaar',
            new_name='aadhaar',
        ),
        migrations.AddField(
            model_name='applicationdoc',
            name='lifeinc_reg',
            field=models.IntegerField(auto_created=True, blank=True, default=48658624640054),
        ),
    ]
