# Generated by Django 4.0.3 on 2022-05-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('lifeInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdoc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
