# Generated by Django 4.0.3 on 2022-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeInsurance', '0002_alter_applicationdoc_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdoc',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
