# Generated by Django 4.0.3 on 2022-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocs',
            name='homeinc_reg',
            field=models.IntegerField(auto_created=True, blank=True, default=48658624640054),
        ),
    ]
