# Generated by Django 3.0.3 on 2022-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocs',
            name='valueOfHome',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applicationdocs',
            name='valueOfHomePlusItems',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
