# Generated by Django 4.0.3 on 2022-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeInsurance', '0002_applicationdocs_homeinc_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_form',
            new_name='claim_docs',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='police_nonTracable_cet',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='policy_documents',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='propertyRateReceipt',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='surveyor_report',
        ),
        migrations.AlterField(
            model_name='claim',
            name='accident_case',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='claim',
            name='witness',
            field=models.CharField(max_length=100),
        ),
    ]
