# Generated by Django 4.0.3 on 2022-04-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='created_by',
        ),
    ]
