# Generated by Django 4.0.3 on 2022-06-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(auto_created=True, blank=True, default=138734354901444851, max_length=100),
        ),
    ]
