# Generated by Django 4.0.3 on 2022-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.IntegerField(auto_created=True, blank=True, default=138734427641545122),
        ),
    ]
