# Generated by Django 4.0.3 on 2022-06-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cover_type', models.CharField(choices=[('1', 'THIRD PARTY ONLY'), ('2', 'THIRD PARTY FIRE AND THEFT'), ('3', 'COMPREHENSIVE')], default='1', max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('num_of_seats', models.PositiveIntegerField()),
                ('value_of_vehicle', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=100)),
                ('extra_TTPD', models.IntegerField(blank=True, null=True)),
                ('excess_buy_back', models.CharField(blank=True, max_length=100, null=True)),
                ('premium', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motoinc_reg', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_licence', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('acc_location', models.CharField(max_length=200)),
                ('claim_doc', models.FileField(upload_to='doc/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mclient', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motoinc_reg', models.IntegerField(auto_created=True, blank=True, default=48658624640054)),
                ('vehicle_registration_number', models.CharField(max_length=100)),
                ('make_of_vehicle', models.CharField(max_length=100)),
                ('vehicle_body_type', models.CharField(max_length=100)),
                ('vehicle_cubic_capacity', models.CharField(max_length=100)),
                ('year_of_manufacture', models.DateField()),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_chassis_num', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.client')),
            ],
        ),
    ]
