# Generated by Django 4.0.3 on 2022-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='motoinc_reg',
            field=models.IntegerField(auto_created=True, blank=True, default=48658624640054),
        ),
    ]
