# Generated by Django 4.0.3 on 2022-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdoc',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
