# Generated by Django 4.0.3 on 2022-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_form', models.FileField(upload_to='doc/')),
                ('policy_documents', models.FileField(upload_to='doc/')),
                ('chassis_number', models.IntegerField(max_length=10)),
                ('FRI_copy', models.FileField(upload_to='doc/')),
                ('loss_incured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_tax_receipt', models.FileField(upload_to='doc/')),
                ('registration_cet', models.FileField(upload_to='doc/')),
                ('repair_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surveyor_report', models.FileField(upload_to='doc/')),
                ('police_nonTracable_cet', models.FileField(upload_to='doc/')),
                ('accident_case', models.FileField(upload_to='doc/')),
                ('withness', models.FileField(upload_to='doc/')),
                ('claim_ref', models.IntegerField(max_length=10)),
            ],
        ),
    ]
