# Generated by Django 3.0.3 on 2022-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0002_alter_applicationdoc_id_alter_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdoc',
            name='licenseType',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D'), ('5', 'E'), ('6', 'F')], default='1', max_length=10),
        ),
    ]
