# Generated by Django 4.0.3 on 2022-05-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0002_alter_applicationdoc_id_alter_claim_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdoc',
            name='premium',
        ),
    ]
