# Generated by Django 4.0.3 on 2022-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0003_applicationdoc_delete_motoinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='chassis_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_ref',
            field=models.IntegerField(),
        ),
    ]
