# Generated by Django 3.0.3 on 2022-05-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('motoInsurance', '0003_applicationdoc_licensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdoc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mclient', to='client.Client'),
        ),
    ]
