# Generated by Django 4.0.3 on 2022-05-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoInsurance', '0003_remove_applicationdoc_premium'),
        ('motoInsurance', '0004_auto_20220531_0025'),
    ]

    operations = [
    ]
